### DISCUSSION TITLE
我想知道一下，字体家族设定之后似乎并没有起效果，还需要做什么？

### DISCUSSION THREAD

**Discussion by 4444zyf** [valor-x/hexo-theme-solitude#287] [Q&A] [answered]
``` yml
font:
  font-size: 16px
  code-font-size: 16px
  font-family: "PingFang SC,Hiragino Sans GB,Microsoft YaHei"
  code-font-family: "Menlo,Monaco,Consolas,Andale Mono,lucida console,Courier New,monospace"
```
以上已经配置在`_config.solitude.yml`中，但似乎仍然是默认的monospace字体？还是说需要字体文件？
