### ISSUE TITLE
[Bug]: 代码块字体变成宋体 & H1等标签居右

### ISSUE THREAD

**Issue by Rean-Schwarze** [valor-x/hexo-theme-solitude#187]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/a1407efb-5528-47a9-93cd-dc456d86b9dc)
如图所示，在官方的演示网站上同样存在代码块字体变宋体的问题；标签居右的原因未知，使用默认主题设置的时候仍然存在这个问题

**Comment by efuo** [comment]
标签居右是更换了 markdown-it 插件

**Comment by efuo** [comment]
字体需要自定义配置
```yaml
font:
  font-size: 16px
  code-font-size: 16px
  font-family: '"PingFang SC","Hiragino Sans GB","Microsoft YaHei"'
  code-font-family: 'monospace, monospace'
```

**Comment by Rean-Schwarze** [comment]
> 字体需要自定义配置
> 
> ```yaml
> font:
>   font-size: 16px
>   code-font-size: 16px
>   font-family: '"PingFang SC","Hiragino Sans GB","Microsoft YaHei"'
>   code-font-family: 'monospace, monospace'
> ```

如果是默认的配置，这两个地方的字体都是宋体
![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/a49f2e49-fbbc-4133-8d05-181e69e7a210)

更改code-font-family第一个字体为consolas，`这里的字体`可以起作用，但是代码块仍然是宋体
```
font:
  font-size: 16px
  code-font-size: 16px
  font-family: '"PingFang SC","Hiragino Sans GB","Microsoft YaHei"'
  code-font-family: 'consolas, consolas'
```
![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/e4c405f1-b220-48ac-84c2-d324c7bba421)
（另外还发现这里有序列表的序号似乎全是1）


> 标签居右是更换了 markdown-it 插件

这里没太懂，可以详细一点吗

**Comment by efuo** [comment]
发链接给我

**Comment by Rean-Schwarze** [comment]
https://rean-schwarze.github.io/p/e042d029/

**Comment by efuo** [comment]
<img width="694" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/74389842/a72cf20a-f47c-4c55-b8af-b7693fc2b6e0">

你电脑没这个字体吧，我这里正常显示

**Comment by efuo** [comment]
标签靠右需要调整一下配置项，参考一下：
```yaml
# markdown-it
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
    - '@renbaoshuo/markdown-it-katex'
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: true
    permalinkClass: 'headerlink'
    permalinkSide: 'left'
    permalinkSymbol: ''
    case: 0
    separator: '-'
  images:
    lazyload: true
    prepend_root: false
    post_asset: false
  inline: false
```

里面使用了ketx插件

**Comment by Rean-Schwarze** [comment]
字体是有的
![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/537fa6ee-4963-4dcf-8772-fe4ffba3ccac)
而且这里的字体显示正常
![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/cab5e5e5-893b-4b84-91bb-e3cd83bc865a)
只有下面代码的字体不正常，然后用手机访问能正常显示。。。好怪啊
同样的字体配置，用回butterfly主题，可以正常显示
![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/d4b24398-d512-40cd-bf0d-2df4e6b22f06)

然后居右的问题，调整了配置项还是没有解决
附一个控制台信息
![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/3a4cb4f9-03ed-4748-ad39-422aa8a9df7d)

**Comment by efuo** [comment]
清一下缓存

**Comment by efuo** [comment]
我这里都显示正常的字体

**Comment by Rean-Schwarze** [comment]
还是不行，不知道哪一环有问题，这里css去掉flex-derection就居左了
![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/f7faa383-ee38-480a-b4a5-09c6aa55ee1b)

**Comment by Rean-Schwarze** [comment]
![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/82b2856a-4970-4207-bbce-be6393037a4f)
字体的话似乎是配置无法影响到最终的css，使用的是默认的monospace

**Comment by efuo** [comment]
> 还是不行，不知道哪一环有问题，这里css去掉flex-derection就居左了 ![image](https://private-user-images.githubusercontent.com/19246285/317793588-f7faa383-ee38-480a-b4a5-09c6aa55ee1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODEzMDQsIm5iZiI6MTcxMTY4MTAwNCwicGF0aCI6Ii8xOTI0NjI4NS8zMTc3OTM1ODgtZjdmYWEzODMtZWUzOC00ODBhLWI0YTUtMDljNmFhNTVlZTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAyNTY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OTkwNGEzYTFjODE1ZmNhNjhlOGFlNzViNGZmYWVjNzNhZjZhZjJjMzc3YjEwOTdlZTFmYTUxZDMxNTg2YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N82ETd22jL97zeVXWHYTRMk3wu-sUalUDHjL_q4KxM8)

打印一下使用的插件
npm ls -dept 0

**Comment by Rean-Schwarze** [comment]
![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/b515cbaa-af2e-4a0b-b200-c1289a91c3bb)

**Comment by Rean-Schwarze** [comment]
字体的话可能是edge的锅了 默认monospace显示就是不行的。。。
![image](https://github.com/valor-x/hexo-theme-solitude/assets/19246285/ac86ef3a-54cc-4e9a-9865-04212b55b4c4)
但是改`solitude/source/css/_global/index.styl`的134行为`font-family consolas, monospace`可以暂时解决

**Comment by efuo** [comment]
```yml
font:
  font-size: 16px
  code-font-size: 16px
  font-family: 'PingFang SC, Hiragino Sans GB, Microsoft YaHei'
  code-font-family: 'monospace, monospace'
```

标题在右是因为使用了markdown-it插件但没有设置 headerlink，需要加上，permalinkSymbol 可以为 ''
