### ISSUE TITLE
[Feature]: 新增功能开关

### ISSUE THREAD

**Issue by son-g0ku** [valor-x/hexo-theme-solitude#244]
### 功能简介

新增文章页面底部的开关及配置选项

### 问题描述

在文章页中的底部，这个 logo 没有找到对应的配置项及开关项，希望能增加对应项目

<img width="1046" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/152959149/76329058-fbd6-49f0-9f38-3a4e2fdb2022">

### 实现效果

1. 增加开关选项；
2. 增加配件选项，能够配置不同的 lgoo

**Comment by efuo** [comment]
已增加配置开关到
```yaml
post:
  default:
      copyright
                author:
                    url: /about/ # 点击头像跳转地址
                    img: # 显示头像，不填写默认显示site_icon
```
