### ISSUE TITLE
[Feature]: footer.links 新增对 html 的支持

### ISSUE THREAD

**Issue by son-g0ku** [valor-x/hexo-theme-solitude#246]
### 功能简介

footer.links 新增对 html 的支持

### 问题描述

目前 footer.link 只能增加链接。希望能够增加对 html 的支持以实现类似 https://www.efu.me/  footer 下方 boringbay 的效果。
如增加 not by ai 的 图目前只能手动修改 Layout，如果增加 html 支持则可以直接 HTML 写入实现。

### 实现效果

目前 footer.link 只能增加链接。希望能够增加对 html 的支持以实现类似 https://www.efu.me/  footer 下方 boringbay 的效果。
如增加 not by ai 的 图目前只能手动修改 Layout，如果增加 html 支持则可以直接 HTML 写入实现。

**Comment by efuo** [comment]
有啊，直接写html标签就可以了，更新最新主题
```yaml
  links:
    - name: <img height="20px" class="nolazyload" src="https://boringbay.com/api/badge/www.efu.me" alt="boringbay"></img>
      url: https://boringbay.com
    - name: 主题
      url: https://github.com/valor-x/hexo-theme-solitude
    - name: 订阅
      url: /atom.xml
```
