### ISSUE TITLE
[Bug]: _data 文件夹内的 .yarm 配置 站内链接

### ISSUE THREAD

**Issue by jiangfeng0103** [valor-x/hexo-theme-solitude#251]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

配置如下
```yaml
essay_list:
  - content: 你好
    date: 2024-04-19 14:06
    link: /posts/4736efd9
```

如果 link 后的链接 不添加  .html ，build后部署到 iis后，访问找不到页面
![2024-04-21_163202](https://github.com/valor-x/hexo-theme-solitude/assets/12807989/5dac083e-8953-4bac-9003-3e67cdde76de)

    link: /posts/4736efd9.html   是否要这样配置？
