### ISSUE TITLE
[Bug]: hexo cl 后找不到essay.yml

### ISSUE THREAD

**Issue by roywhite98** [valor-x/hexo-theme-solitude#253]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

![image](https://github.com/valor-x/hexo-theme-solitude/assets/60284470/29e04750-70c3-4629-a193-9ff2d195f1b4)
![image](https://github.com/valor-x/hexo-theme-solitude/assets/60284470/84462d74-e3e4-4234-8ceb-687ca057a65b)
hexo cl 后找不到essay.yml，关闭says hexo s成功后，开启says.enable: true，不clean的情况下 hexo s又能够成功读到essay.yml

### 终端日志 📒

无

**Comment by efuo** [comment]
改成 .yaml 后缀

**Comment by roywhite98** [comment]
> 改成 .yaml 后缀
嗯 似乎不是这种问题，打算放弃内置的essay了
![image](https://github.com/valor-x/hexo-theme-solitude/assets/60284470/c73e9edc-647b-486e-9a94-fe8a809116c3)

**Comment by efuo** [comment]
<img width="1252" alt="image" src="https://github.com/valor-x/hexo-theme-solitude/assets/74389842/f2281430-2130-4a28-8e43-7548b156f60f">

```yaml
essay_list:
  - content: 视频播放测试！
    date: 2023-10-31 15:32
    video:
      bilibili: BV1Cv4y1p717
  - content: 音乐播放测试！
    date: 2023-10-31 15:32
    aplayer:
      server: netease
      id: 571340283
  - content: 主题交流群已建立！
    date: 2023-10-31 15:32
    image:
      - https://7.isyangs.cn/1/65e9de42e32cd-1.png
    link: https://efu.me/
```
